%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\VoltageDivider\Ряд.xlsx
%    Worksheet: Лист1
%
% Auto-generated by MATLAB on 28-Oct-2020 12:06:39

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Лист1";
opts.DataRange = "A2:G193";

% Specify column names and types
opts.VariableNames = ["E3", "E6", "E12", "E24", "E48", "E96", "E192"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
series = readtable("D:\VoltageDivider\Ряд.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts